networks:
  boursenet:
    driver: bridge

services:
  db:
    image: reg.undercloud.cri.epita.fr/docker/timescale/timescaledb:latest-pg16
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - "5432:5432"
    networks:
      - boursenet
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=bourse
      - POSTGRES_USER=ricou
      - POSTGRES_PASSWORD=monmdp
    volumes:
      - /srv/libvirt-workdir/bourse/timescaledb:/var/lib/postgresql/data/timescaledb
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ricou -d bourse -h localhost"]
        interval: 6s
        timeout: 3s
        retries: 5

  analyzer:
    image: my_analyzer
    depends_on:
      db:
        condition: service_healthy
    networks:
      - boursenet
    volumes:
      - /srv/libvirt-workdir/bourse/data:/home/bourse/data/

  dashboard:
    image: my_dashboard
    networks:
      - boursenet
    ports:
      - "8050:8050"
