name: "Package the project into a tar.gz archive"
on:
  push:
    branches: [ main ]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract the archive architecture
        run: |
          wget https://www.lrde.epita.fr/~ricou/pybd/projet/bourse.tgz;
          mkdir release;
          cd release;
          mv ../bourse.tgz . && tar -xf bourse.tgz
          cd bourse
          cp -r ../../bourse/analyzer/*.py analyzer/
          cp -r ../../bourse/dashboard/*.py dashboard/
          cd ..
          tar -cf bourse-release.tar.gz bourse/
          cd ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: release/bourse-release.tar.gz
